#!/usr/bin/env python3
"""
Generate the cryptographic secrets required by Match Minds.

Emits values for two variables in `.env`:

    DJANGO_SECRET_KEY   512-bit (64-byte) random secret, urlsafe-base64 encoded
    ENCRYPTION_KEY      AES-256-GCM key for field-level encryption (Fernet)

Usage
-----
    python scripts/generate_secret_key.py

Then paste the output into your `.env` file, or let the script write it
directly:

    python scripts/generate_secret_key.py --write-env

    # only print the keys, don't touch .env
    python scripts/generate_secret_key.py --dry-run

Notes
-----
`cryptography` is listed in requirements.txt, but this script falls back to
the standard library so it still works in a bare virtualenv before the
dependencies are installed. Both paths use `os.urandom`, which reads from the
OS cryptographically secure random source.
"""

from __future__ import annotations

import argparse
import base64
import os
import re
import sys
from pathlib import Path

DJANGO_SECRET_KEY_BYTES = 64  # 512 bits, as required by the spec
FERRER_KEY_BYTES = 32  # AES-256


def _urlsafe(data: bytes) -> str:
    """Base64url-encode without padding — Django's preferred format."""
    return base64.urlsafe_b64encode(data).decode("ascii").rstrip("=")


def generate_django_secret_key() -> str:
    """Return a 512-bit random secret key."""
    return _urlsafe(os.urandom(DJANGO_SECRET_KEY_BYTES))


def generate_encryption_key() -> str:
    """
    Return a Fernet-compatible AES-256 key.

    Prefers `cryptography` so the key is guaranteed to match exactly what
    django-encrypted-model-fields will accept. Falls back to a manual
    urlsafe-base64 encoding of 32 random bytes, which is byte-for-byte the
    same construction Fernet uses.
    """
    try:
        from cryptography.fernet import Fernet

        return Fernet.generate_key().decode("ascii")
    except ImportError:
        return _urlsafe(os.urandom(FERRER_KEY_BYTES))


def render(secret_key: str, encryption_key: str) -> str:
    return (
        "# Generated by scripts/generate_secret_key.py — do not commit real values\n"
        f"DJANGO_SECRET_KEY={secret_key}\n"
        f"ENCRYPTION_KEY={encryption_key}\n"
    )


def write_to_env(env_path: Path, secret_key: str, encryption_key: str) -> int:
    """
    Replace existing values in .env, or append them if absent.

    Returns the number of variables written.
    """
    if not env_path.exists():
        print(f"error: {env_path} not found — run: cp .env.example .env", file=sys.stderr)
        return 1

    content = env_path.read_text(encoding="utf-8")
    replacements = {
        "DJANGO_SECRET_KEY": secret_key,
        "ENCRYPTION_KEY": encryption_key,
    }
    written = 0

    for name, value in replacements.items():
        # Match an active assignment; leave commented-out placeholders alone.
        pattern = re.compile(rf"^{name}=.*$", re.MULTILINE)
        if pattern.search(content):
            content = pattern.sub(f"{name}={value}", content)
        else:
            content = f"{name}={value}\n" + content
        written += 1

    env_path.write_text(content, encoding="utf-8")
    print(f"updated {written} variables in {env_path}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate DJANGO_SECRET_KEY and ENCRYPTION_KEY for .env"
    )
    parser.add_argument(
        "--write-env",
        action="store_true",
        help="write the keys directly into .env instead of printing them",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="force printing the keys, never writing to .env",
    )
    args = parser.parse_args()

    secret_key = generate_django_secret_key()
    encryption_key = generate_encryption_key()

    if args.write_env and not args.dry_run:
        repo_root = Path(__file__).resolve().parent.parent
        return write_to_env(repo_root / ".env", secret_key, encryption_key)

    print(render(secret_key, encryption_key))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())